"use client";
import { useState } from "react";
import { TriangleAlert } from "lucide-react";
import type { ProductoConStock } from "@/components/stock-manager";
import { ConfigProductoStock } from "@/components/stock-configuracion";
export function AlertasStock({ items, administrador, global }: { items: ProductoConStock[]; administrador:boolean; global:number|null }) {
  const [producto,setProducto] = useState<ProductoConStock|null>(null);
  const [busqueda,setBusqueda] = useState(""); const [todas,setTodas] = useState(false);
  const alertas=items.filter(p=>p.alertaActiva&&p.stockLocal<p.stockMinimo);
  const visibles=(todas?items:alertas).filter(p=>`${p.nombre} ${p.sku}`.toLowerCase().includes(busqueda.toLowerCase()));
  return <><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">Alertas de stock</h2><p className="text-sm text-slate-500">{alertas.length} productos para reponer</p></div>{administrador&&<label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={todas} onChange={e=>setTodas(e.target.checked)} />Mostrar todos para configurar</label>}</div><input className="input mb-4" value={busqueda} onChange={e=>setBusqueda(e.target.value)} aria-label="Buscar alertas por producto o código" placeholder="Buscar producto o código…" /><ul className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{visibles.map(p=>{const bajo=p.alertaActiva&&p.stockLocal<p.stockMinimo;return <li key={p.id} className={`card p-4 ${bajo?"border-amber-200 bg-amber-50":"border-slate-200"}`}><div className="flex items-start gap-3"><TriangleAlert aria-hidden="true" className={`mt-0.5 h-4 w-4 shrink-0 ${bajo?"text-amber-700":"text-slate-400"}`} /><div className="min-w-0"><p className="text-xs font-medium text-slate-500">{!p.alertaActiva?"Alerta desactivada":p.stockLocal===0&&bajo?"Sin stock":bajo?"Stock bajo":"Stock suficiente"}</p><p className="mt-1 break-words font-semibold">{p.nombre}</p><p className="mt-1 text-xs text-slate-500">{p.sku}</p><p className="mt-3 text-sm">Disponible: <strong>{p.stockLocal}</strong> · Mínimo: {p.stockMinimo}</p>{administrador&&<button className="btn-ghost mt-3 border border-slate-200 text-xs" onClick={()=>setProducto(p)}>Configurar alerta y precio</button>}</div></div></li>})}</ul>{!visibles.length&&<p className="card p-6 text-sm text-slate-500">{busqueda?"No hay productos que coincidan con la búsqueda.":"No hay alertas de stock bajo en esta vista."}</p>}{producto&&<ConfigProductoStock producto={producto} global={global} cerrar={()=>setProducto(null)} />}</>;
}
