"use client";
import { Overlay } from "@/components/overlay";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import type { ProductoConStock } from "@/components/stock-manager";
import { guardarMultiplicadorStock, configurarProductoStock } from "@/app/stock-actions";
import { money } from "@/lib/format";
export function MultiplicadorStock({ valor }: { valor: number | null }) {
  const [activo,setActivo] = useState(valor !== null);
  const [factor,setFactor] = useState(String(valor ?? 2));
  const [mensaje,setMensaje] = useState(""); const [pendiente,iniciar] = useTransition(); const router = useRouter();
  return <section className="card mb-5 p-5"><h2 className="font-semibold">Precio de venta en la carga de stock</h2><p className="mt-1 text-sm text-slate-500">Precio de venta = costo nuevo × multiplicador. Se aplica en cada carga; un multiplicador específico del producto tiene prioridad.</p><form className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-[minmax(0,1fr)_minmax(10rem,16rem)_auto] lg:items-end" action={() => iniciar(async()=>{const r=await guardarMultiplicadorStock(activo?Number(factor):null);setMensaje(r.ok?"Configuración guardada.":r.error);if(r.ok)router.refresh();})}><label className="flex min-h-11 items-center gap-3 rounded-xl border border-slate-200 px-3 py-2 text-sm"><input type="checkbox" checked={activo} onChange={e=>setActivo(e.target.checked)} />Usar multiplicador general</label><div><label className="label" htmlFor="factor-stock">Multiplicador sobre el costo</label><input id="factor-stock" type="number" min="0.0001" max="1000" step="0.0001" disabled={!activo} required={activo} value={factor} onChange={e=>setFactor(e.target.value)} className="input h-11 w-full" /></div><button disabled={pendiente} className="btn-primary sm:col-span-2 lg:col-span-1">{pendiente?"Guardando…":"Guardar regla"}</button></form><p className="mt-3 rounded-xl bg-slate-50 p-3 text-sm leading-relaxed text-slate-500">Ejemplo: costo {money(1000)} × {factor || "0"} = {money(1000*Number(factor))}. Esta configuración no cambia los precios actuales hasta la próxima carga.</p>{mensaje&&<p role="status" className="mt-2 text-sm">{mensaje}</p>}</section>;
}
export function ConfigProductoStock({ producto: p, global, cerrar }: { producto: ProductoConStock; global: number|null; cerrar: ()=>void }) {
  const [factor,setFactor] = useState(String(p.multiplicadorCosto ?? global ?? 2));
  const [propio,setPropio] = useState(p.multiplicadorCosto != null);
  const [calcular,setCalcular] = useState(false); const [error,setError] = useState(""); const [pendiente,iniciar] = useTransition(); const router = useRouter();
  const efectivo = propio ? Number(factor) : global;
  return <Overlay className="overlay"><form className="sheet p-5 sm:max-w-xl" role="dialog" aria-modal="true" aria-labelledby="config-producto" action={fd=>iniciar(async()=>{setError("");const r=await configurarProductoStock(p.id,{stockMinimo:Number(fd.get("minimo")),alertaActiva:fd.get("alerta")==="on",precioVenta:Number(fd.get("venta")??p.precioVenta),multiplicador:propio?Number(factor):null,calcularAhora:calcular});if(!r.ok){setError(r.error);return;}cerrar();router.refresh();})}><h2 id="config-producto" className="text-lg font-semibold">Precio y alertas</h2><p className="mt-1 font-medium text-slate-600">{p.nombre}</p><p className="mt-2 text-sm text-slate-500">Costo actual: {money(p.precioCompra)} · Stock disponible: {p.stockLocal}</p><div className="mt-5 space-y-4"><label className="flex items-center gap-2 text-sm"><input name="alerta" type="checkbox" defaultChecked={p.alertaActiva} />Activar alerta de stock bajo</label><div><label className="label" htmlFor="stock-minimo-config">Mínimo de stock</label><input id="stock-minimo-config" name="minimo" type="number" min="0" step="1" defaultValue={p.stockMinimo} required className="input" /><p className="mt-1 text-xs text-slate-500">Se alerta cuando el disponible está por debajo de este mínimo. Se aplica por sucursal o al total de la vista elegida.</p></div><div><label className="label" htmlFor="venta-config">Precio de venta actual</label><input id="venta-config" name="venta" type="number" min="0" step="0.01" defaultValue={p.precioVenta} disabled={calcular} required className="input" /></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={propio} onChange={e=>{setPropio(e.target.checked);if(!e.target.checked&&global===null)setCalcular(false);}} />Usar multiplicador propio en las próximas cargas</label>{propio?<div><label className="label" htmlFor="factor-producto">Multiplicador sobre el costo</label><input id="factor-producto" type="number" min="0.0001" max="1000" step="0.0001" value={factor} onChange={e=>setFactor(e.target.value)} required className="input" /></div>:<p className="text-xs text-slate-500">{global===null?"Sin regla general: las cargas conservan las opciones de revisión actuales.":`Usa la regla general: costo × ${global}.`}</p>}{efectivo!==null&&<><p className="rounded-xl bg-lime/15 p-3 text-sm">{money(p.precioCompra)} × {efectivo} = <strong>{money(p.precioCompra*efectivo)}</strong></p><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={calcular} onChange={e=>setCalcular(e.target.checked)} />Aplicar este cálculo al precio actual al guardar</label></>}</div>{error&&<p role="alert" className="mt-3 text-sm text-rose-600">{error}</p>}<div className="mt-5 flex gap-2"><button disabled={pendiente} className="btn-primary">{pendiente?"Guardando…":"Guardar configuración"}</button><button type="button" disabled={pendiente} className="btn-ghost" onClick={cerrar}>Cancelar</button></div></form></Overlay>;
}

